### ISSUE TITLE
(1.12.2) Crash upon launch

### ISSUE THREAD

**Issue by ItsApache** [DaedalusGame/BetterWithAddons#71] opened 2018-01-21 23:49 UTC
Cause: https://pastebin.com/YDP6VTnz

Forge Version: 1.12.2 - 14.23.1.2600

**Comment by DaedalusGame** [comment] 2018-01-22 00:10
duplicate of #70 already uploading a fix to curse

**Closed by DaedalusGame** 2018-01-22 00:10 UTC
